# Conexiune la baza de date - hostname-ul trebuie să fie numele serviciului din docker-compose (de ex. "db")
spring.datasource.url=jdbc:postgresql://db:5432/barber_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver




# Inițializare și Hibernate
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

# Activează profilul corespunzător
spring.profiles.active=dev

# Fișiere mari (upload imagine)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT config
jwt.secret=L9qsw53EIQ8vRJHH6E8aGgB2P/FRvvu3iL3CqHx/7IjkeWJAVh1YF7qXqzR4gAvTzZP+zGU7VuhtmK+OQEXAyQ==

# Logging (ex: controller debug)
logging.level.com.example.demo.controller.AnuntController=DEBUG

# Maildev config (dacă îl folosești)
spring.mail.host=maildev
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
 spring.security.enabled=false